### ISSUE TITLE
Devtools should let me run spinning_cube without loading the DefaultViewManager

### ISSUE THREAD

**Issue by iansf** [domokit/devtools#10]
Devtools ideally will avoid the following issue I'm having with skydb.  skydb is not compatible with running spinning_cube, since spinning_cube expects to be the first thing loaded, whereas skydb creates a DefaultViewManager before launching spinning_cube.

To test this issue, you can attempt the following command with an Android device attached:

```sky/tools/skydb start out/android_Debug mojo:spinning_cube --gdb && sky/tools/skydb gdb_attach```

The app should crash in gfx::GLSurface::InitializeOneOff because InitializeOneOff gets called twice, once from DefaultViewManager and the second time from NativeViewportImpl.

Instead, if you launch on Android with the following command, spinning_cube launches and runs fine, but is not debuggable:

adb shell am start -W -S -a android.intent.action.VIEW -n org.chromium.mojo.shell/.MojoShellActivity --esa parameters 'mojo:spinning_cube,--origin=http://localhost:9999/out/android_Debug'

**Comment by ppiet** [comment]
Thanks for the feature request! The devtools-based stack, and mojo_shell.py in particular, 'supports' apps that run without window manager - ie. does not impose the presence of one. For instance, you can try running:

```
mojo/tools/mojo_shell.py mojo:spinning_cube
```

Please feel free to reopen the issue should you encounter any problems!
