### ISSUE TITLE
Tracing integration

### ISSUE THREAD

**Issue by tonygentilcore** [domokit/devtools#4]
Skydb has some functionality to start/stop tracing and pull the trace to the host. It'd be useful if devtools could do the same.

**Comment by ppiet** [comment]
In Sky they have this nifty sky_debugger. It is a native mojo application that puts up a http_server exposing a few urls. In response to loading these urls, debugger starts/stops tracing and profiling.

I think that this debugger app is useful in general for anyone running mojo_shell. I think we could:

 - pull Sky debugger from sky/tools/debugger -> services/debugger
 - add support in devtools for setting it up when the shell is run
 - add a tiny script in devtools for sending interactive commands to debugger (`debugger start_tracing`?)

wdyt?

@tonygentilcore @qsr @eseidelGoogle

**Comment by tonygentilcore** [comment]
sgtm

I hear there's also been some talk of integrating trace viewer into the dart observatory. It'd be nice to design the CLI such that it'd be easy for the observatory to invoke `debugger` so that developers could do everything from the observatory if they like. /cc @sethladd

**Comment by sethladd** [comment]
cc @johnmccutchan

**Comment by ppiet** [comment]
We now have the [debugger cli](https://github.com/domokit/devtools/blob/master/debugger), and mojo_shell.py starts mojo:debugger by default (using shell_arguments.ConfigureDebugger(), available for any embedder of the devtoolslib).
