### ISSUE TITLE
Unable to pass argument to mojo:url_response_disk_cache on android.

### ISSUE THREAD

**Issue by qsr** [domokit/devtools#43]
Consider the following command line:

`./mojo/devtools/common/mojo_run '--args-for=mojo:url_response_disk_cache --clear' https://core.mojoapps.io/spinning_cube.mojo  --verbose --android`

If you look at URLResponseDiskCacheApp::Initialize, the --clear argument is not passed.

Running the same command line on Linux (removing --android) works perfectly fine.

**Comment by ppiet** [comment]
It looks like this is a bug in shell initialization - moving to https://github.com/domokit/mojo/issues/411 .
