### ISSUE TITLE
Find out why benchmarking dart apps times out on Linux

### ISSUE THREAD

**Issue by ppiet** [domokit/devtools#45]
This happens only on Linux and only for Dart apps. The benchmark run produces valid results, but shell fails to terminate on its own.

**Comment by zanderso** [comment]
TestUsingTracingApp should call close() when the app is finished.

**Comment by zanderso** [comment]
See //examples/dart/wget/lib/main.dart for an example of an app that does some work in initialize() and then quits.

**Comment by ppiet** [comment]
Thanks for a pointer, but there's more to that I think.

The app should not be required to ever "finish". In a benchmark run, the only primordial app is `benchmark.mojo`, and it in turn connects to the app being benchmarked. The shell should terminate when `benchmark.mojo` terminates. The c++ app being benchmarked doesn't terminate either, and yet the shell terminates correctly.

**Comment by zanderso** [comment]
That Dart app has a handle open to the shell that it will never close on its own without the app calling close(). It should be closed properly if the other end is closed, though.

There are also two problems with waitForMilliseconds():
1. The handles allocated there are leaked.
2. You should use Dart's Timer class in dart:async instead.

**Comment by zanderso** [comment]
Investigated this further. The problem was not closing the app, but rather the periodic timer must be canceled. This should be fixed by: https://codereview.chromium.org/1371853002/

**Comment by ppiet** [comment]
Nice, thanks for looking into this! Do you know why the behavior differs between Linux and Android?

**Comment by zanderso** [comment]
Fixed by https://github.com/domokit/mojo/commit/5543c19aeb87673f249164be7781052388bd0dce
