### ISSUE TITLE
mojo_benchmark feature request: measure median, and e.g. 10th percentile, 90th percentile, etc.

### ISSUE THREAD

**Issue by zanderso** [domokit/devtools#49]
These metrics would give a fuller picture than a simple average.

**Comment by zanderso** [comment]
@emembrives @ppiet @qsr I can also take a stab at this if that would help?

**Comment by ppiet** [comment]
Sure, by all means. I think that `mojo_benchmark` should accept parameters for the number of runs (1 by default), run the benchmark multiple times and compute the statistics. 

Note that you will need to teach `mojo_benchmark` to actually understand the output from benchmark.mojo, but that should not be a big trouble.

I'm in MTV today and next week, feel free to grab me any time.

**Comment by ppiet** [comment]
To clarify for historical record: there are two dimensions across which we could calculate aggregates:

 - over multiple occurences of the targeted event (within one run)
 - over results of multiple runs

Here @zanderso needed the former and it's landed - https://codereview.chromium.org/1394963002 . Filed https://github.com/domokit/devtools/issues/54 for the latter and closing this bug.
