### ISSUE TITLE
Timeout for Android shell connection is too short to go through permission prompts.

### ISSUE THREAD

**Issue by ppiet** [domokit/devtools#56]
With the new permission model in L, the first run of the shell requires granting the runtime permissions of the app. `android_shell.py` doesn't give the user enough time to go through the permission prompts.

We probably want at least to increase the timeout and make the error message more understandable. Current error:

```
line 129, in _wait_for_fifo
    raise Exception("Unable to find fifo.")
Exception: Unable to find fifo.
```

@tonygentilcore @gmesch

**Comment by qsr** [comment]
We can use
adb shell am grant PERMISSION
to grant the permissions after installing the application.
