### ISSUE TITLE
Avoid installing the shell APK every time we run on Android

### ISSUE THREAD

**Issue by ppiet** [domokit/devtools#7]
There are at least two approaches to avoiding shell APK re-install on every run:

 - calculate the hash on the host and store it somewhere on the device (like Sky's shelldb [does](https://codereview.chromium.org/1149113005))
 - push a hashing binary onto the device and calculate the hash on the device (like Chromium does)

The first way doesn't require root or additional binaries and I'm inclined to go for it.

@tonygentilcore @qsr

**Comment by qsr** [comment]
First way seems fine to me.

**Comment by tonygentilcore** [comment]
+1 to the first
