### ISSUE TITLE
Run on Android user builds with no root.

### ISSUE THREAD

**Issue by ppiet** [domokit/devtools#8]
Currently we require adb root to run shell on Android. This should not be necessary.

AFAIU we need root to retrieve the shell output through the fifo file - we should probably check if the device is rooted and just run without piped shell output if this is not the case.

@tonygentilcore @qsr

**Comment by tonygentilcore** [comment]
I imagine gdb and a few other things might need root too. But I really like your design of gracefully degrading and ensuring the typical flow works without root. We can fail with a user-friendly message if a particular feature requires root.
